### ISSUE TITLE
[enhancement] TypeScript support for useAsyncValue

### ISSUE THREAD

**Issue by nmatanski** [stargaze-co/react-router-typesafe#11]
Can you add support for `useAsyncValue` similar to the one for `Await`'s render function?

**Comment by fredericoo** [comment]
The original remix API has its type set to `unknown` and I think I agree: it’s very hard to tell the closest ancestor’s type.

Introducing a type parameter to the function would "help" by providing some type hints as to what this value would represent, but no actual processing happens there. Unline `useLoaderData`  or `useActionData`, where you pass in the type of the loader and it infers from json, defer, response and other returns what the type should be, `useAsyncValue` would simply return the value itself, being equivalent to simply casting it.

Unless you have a smarter solution, I’d recommend sticking with:

1. the Await component, passing the awaited props as normal:
```tsx
<Await resolve={aPromise}>
{ awaited => <MyComponent data={awaited} /> }
</Await>
```
2. casting it
```tsx
const MyComponent = () => {
  const value = useAsyncValue() as Awaited<(typeof loader)['property']>;
}
```

I’m open to feedback!

**Comment by nmatanski** [comment]
Off-topic, but what do you think about `useRouteError`'s unknown type? Similar case? I just wish RR6 was implemented differently with more generics in mind, but be careful what you wish for with RR I guess or RR7 will be a complete reboot again..

**Comment by fredericoo** [comment]
> Off-topic, but what do you think about `useRouteError`'s unknown type? Similar case? I just wish RR6 was implemented differently with more generics in mind, but be careful what you wish for with RR I guess or RR7 will be a complete reboot again..

Same thing! Like `catch` in try catch blocks, unknown is the most certain assumption one can make against thrown values. 

I think we’ve seen the last of major versions though! After Remix they have taken such a beautiful turn with incremental, non breaking upgrades. There are some react router 7 [future flags](https://reactrouter.com/en/main/guides/api-development-strategy#current-future-flags) already, you can start migrating incrementally now!

I couldn’t be happier with the direction things are going with Remix/React Router, and honestly cannot wait to deprecate this library, but I feel like it’ll be some time until we can surgically alter the internal types. Maybe I should have another stab at implementing type-hinted loaders and actions again? Last time I tried I couldn’t get it to work without chaning 10+ files and I wasn’t sure I wasnt breaking any Remix APIs in the process.

**Comment by fredericoo** [comment]
Any further discussion points feel free to open another issue
