### ISSUE TITLE
How about adding the support for the "useRouteLoaderData" as well?

### ISSUE THREAD

**Issue by nemonemi** [stargaze-co/react-router-typesafe#2]
I have a use case where a deeply nested component need access to the data defined in the loader, and for that we need the hook `useRouteLoaderData`, which this library does not currently support.

Is this something you are willing to add?

I am at version 1.3.0, and while I can see it in the source code, it is not being exported for consumption.
https://github.com/stargaze-co/react-router-typesafe/blob/2a25b3ed19602913d5fdfba19907ef65005d01e9/src/loader.ts#L20C14-L20C32

**Comment by fredericoo** [comment]
Oh no! I had forgotten to export it. It should be fixed now on `1.3.1` ◡̈
