### ISSUE TITLE
How to get errors without response type for useActionData

### ISSUE THREAD

**Issue by ameyer117** [stargaze-co/react-router-typesafe#4]
Hello & thank you for creating this library, its been a blessing.

Just wondering how I can best get the errors that are returned from my `useActionData` hook if the action had also had a redirect for successful use cases?

For example, here is the type I see in that case:
```typescript
const actionData: ActionData<({request}: ActionFunctionArgs<any>) => Promise<Response | {status: number, error: string}>>
  ```
  
  Coming from this relevant code:
  ```typescript
  const actionData = useActionData<typeof contactAction>()
  ```
  
  ```typescript
  export const contactAction = makeAction(async ({request}: ActionFunctionArgs) => {
    const data = await request.formData()
    const submission = {
        email: data.get('email') as string,
        message: data.get('message') as string
    }

    if(submission.message.length < 10) {
        return {
            status: 400,
            error: 'Your message must be at least 10 characters long.'
        }
    }

    return redirect('/')
})
```

If my understanding is correct, the component will never "see" the Response anyways, so it can be omitted? Thanks in advance.

**Comment by fredericoo** [comment]
Well spotted ◡̈ that Response object should not have ended in the response of `useActionData`. Will fix and write some tests tomorrow.

> tip: you dont have to annotate the arguments for the action if you use `makeAction`; they’ll come pre-typed for you ;)

**Comment by fredericoo** [comment]
Can you check if v.1.3.4 fixes the issue for you?

**Comment by ameyer117** [comment]
Thanks for the quick fix and tips! It works exactly like Remix, and I'm thrilled about this library. Thanks again!
